### ISSUE TITLE
Settings周りの設定を変更した方が良いと思うの

### ISSUE THREAD

**Issue by kkiyama117** [Zoniisan/LION#7]
djangoのherokuの設定、イケメンすぎる！と思ってコードパクろうと思っていたら(クズ)
ちょいちょい改善点見つけたので自分Reviewいいっすか

**Comment by kkiyama117** [comment]
requirements.txtに自分のPCのpipのプラグイン全部書いてると多分Herokuや(今後導入するであろう)pytestとかGithub上でのテストで全部読み込もうとするから尋常じゃない時間がかかると思われる

**Comment by Zoniisan** [comment]
はい、仮想環境を新たに組んで最小限のもののみrequirement.txtに書くことにしました。（なんかherokuに対応していないversionのものもインストールしようとしていたようで、エラーを吐きまくってしまいました。それで最小限にとどめるやり方を調べただけです）なお、コードがイケメンに見えるとのことですが、全部他のサイトから知識をつぎはぎしただけです。

**Comment by kkiyama117** [comment]
おつ！

**Comment by kkiyama117** [comment]
天才
