### ISSUE TITLE
助けてkkiyama

### ISSUE THREAD

**Issue by Zoniisan** [Zoniisan/LION#9]
* settings のsecret key削除
* migrationsなどの削除（現在.gitignoreがなあなあになっていてよくわからなくなっている）
* postgresqlに対応してほしい
* herokuに上げるときだけdebug =falseにしてほしい

developにpull requestしておいてください。確認次第masterにもリリースします
（masterブランチに上げると自動でdeployされますので……）

また、こちらのherokuサーバーをいじらなければならないときはslackでその旨教えてください

お忙しい中恐縮ですがここ2週間くらいこれしかやっていなくて、そろそろ大学の勉強しないと大変なので……

**Comment by kkiyama117** [comment]
settings -> Branches -> Protected branches の　Choose a branch -> master -> protected this branch -> Require pull request reviews before merging

**Comment by kkiyama117** [comment]
Restrict who can push to this branch で自分を追加すれば自分はやりたい放題出来るはず

**Comment by Zoniisan** [comment]
* Require pull request reviews before mergingを「有効」にしました
* Restrict who can push to this branchはorganizationにのみ適用できるようです。今回はZoniisan個人のリポジトリなのでできません。

**Comment by kkiyama117** [comment]
なーるほど

**Comment by kkiyama117** [comment]
# 解決済
- herokuに上げるときだけdebug =falseにしてほしい
# すぐ出来る
- settings のsecret key削除
- migrationsなどの削除（現在.gitignoreがなあなあになっていてよくわからなくなっている）
# 皆でやらないとできない
- postgresqlに対応してほしい

**Comment by Zoniisan** [comment]
postgresqlには対応し、DBもうまいこと動くようになりました。
デプロイしたサイトを参照願います。https://obscure-oasis-85774.herokuapp.com/

とりあえず魚の写真をいれてありますが、adminサイトから変更できます。

**Comment by Zoniisan** [comment]
![image](https://user-images.githubusercontent.com/33656281/33807130-4d16cf90-de15-11e7-8901-c6b02ab8c5cd.png)

**Comment by Zoniisan** [comment]
ありがとうございました
